development:
  bucket: musthave-new
  access_key_id: AKIAIELUBMUNHPAY37KQ
  secret_access_key: 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

test:
  bucket: musthave-new
  access_key_id: AKIAIELUBMUNHPAY37KQ
  secret_access_key: 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

production:
  bucket: musthave-new
  access_key_id: AKIAIELUBMUNHPAY37KQ
  secret_access_key: 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